### ISSUE TITLE
Close all PRs that originate from atom/atom and aren't created by maintainers

### ISSUE THREAD

**Issue by winstliu** [atom/mistaken-pull-closer#2]
_Any_ Atom branch that is turned into a PR by a non-maintainer is unintentional, since they can't do anything with it.

Looks like the pull_request context has a `user` field, and maybe they can be checked for membership using https://developer.github.com/v3/orgs/members/#check-membership?

**Comment by lee-dohm** [comment]
Fixed in #3 and #6. The check is against push access, not membership ... but that should work the way we expect.
