### ISSUE TITLE
Accidentally closing Greenkeeper pull requests

### ISSUE THREAD

**Issue by zeke** [atom/mistaken-pull-closer#9]
Greenkeeper is opening PRs on Electron's website, but they're getting closed: https://github.com/electron/electron.atom.io/pull/827

Ideas about how to fix this:

- Whitelist branches that start with `greenkeeper/`
- Whitelist the @greenkeeper user
- Something else?

**Comment by lee-dohm** [comment]
Non-atom-org repositories are using probot/mistaken-pull-closer, so I reopened this over there: https://github.com/probot/mistaken-pull-closer/issues/2

**Comment by lee-dohm** [comment]
I'm going to shut down the Atom version soon and move the atom org over to the Probot version as well.
